import sys, pickle; sys.path.insert(0,".build")
from nbbuild import md, code
C=pickle.load(open(".build/_ch04.pkl","rb")); A=C.append

A(md(r'''## 4.7 Physical Security as Social Engineering's Partner

Social engineering frequently has a physical destination: the goal of a convincing pretext is often to
get a person, or the attacker, through a door. Physical security is therefore inseparable from the human
element, and this section treats the physical controls that social engineers try to defeat. Physical
threats range from the natural (fire, flood, storms) to the man-made (theft, vandalism, destruction), and
a stolen executive laptop may matter far less for the hardware than for the plans it contains.

**Locks** are the most familiar physical control, and understanding their weaknesses is sobering.
*Warded locks*, the basic padlock, offer little security and can be opened with a shaped piece of metal.
*Pin-tumbler locks* are stronger but are defeated by **lock picking**, manipulating the pins with a
tension wrench and pick, by **bump keys**, a specially cut key that is tapped to jolt the pins into
alignment, or by **shimming** a padlock's latch. Even electronic locks have failed spectacularly; a
widely reported vulnerability in a brand of hotel door lock allowed it to be opened with an inexpensive
microcontroller plugged into a port on the lock's base. Locks are graded by quality (Grade 1 commercial
being the strongest, Grade 3 the weakest), and keypad or combination locks add the risk of **shoulder
surfing**, countered by visibility shields and delay alarms.

Beyond locks, organizations use layered **facility and area controls**: fences, gates, bollards,
security lighting, guards, dogs, closed-circuit television (CCTV) cameras, solid-core doors with
reinforced hinges and strike plates, walls that run floor to ceiling, and monitored windows. A
**mantrap** (an access-control vestibule) is a small space with two interlocking doors that permits only
one person through at a time, directly countering tailgating. Lower-technology exposures matter too:
unshredded documents invite dumpster diving (cross-cut shredders are far harder to reconstruct than
strip-cut), and discarded fax ribbons or unattended faxes leak documents. The unifying principle, as in
Chapter 1, is *physical defense in depth*: controls layered at the perimeter, the building, the work
area, and the equipment, so that defeating one does not grant the attacker their goal. Every one of these
controls exists because a determined person, often aided by a social-engineering pretext, will test it.
'''))

A(md(r'''## 4.8 Authentication Factors

Many social-engineering attacks ultimately aim to defeat authentication, so understanding the factors of
authentication, and why combining them helps, follows naturally from the attacks. Authentication
mechanisms draw on three classic factors. The first is **something you know**, such as a password or PIN;
it is cheap but vulnerable to guessing, phishing, and shoulder surfing. The second is **something you
have**, such as a hardware token, smart card, or a code generated by a phone app; it resists remote
guessing but can be lost or, in some forms, intercepted. The third is **something you are**, a
*biometric* such as a fingerprint, facial geometry, retina or iris scan, or voiceprint; it is convenient
and hard to share but cannot be changed if compromised and raises privacy concerns. Additional factors
sometimes cited include *somewhere you are* (location) and *something you do* (behavior).

The power of these factors comes from combining them. **Multi-factor authentication (MFA)** requires
evidence from two or more distinct factors, so that an attacker who phishes a password still cannot log
in without the second factor. MFA dramatically reduces the success of credential phishing, which is
exactly why modern social engineers have shifted to attacking MFA itself, through *MFA-fatigue* attacks
that bombard a victim with approval prompts until they accept one, through real-time relay of one-time
codes, and, as recent help-desk attacks show, through tricking support staff into resetting or
re-enrolling a victim's MFA entirely. The lesson is that MFA is essential but not a panacea: phishing-
resistant factors (such as hardware security keys based on the FIDO2 standard) and hardened help-desk
verification are needed to close the gaps that social engineers now target.
'''))

A(md(r'''## 4.9 Defending Against Social Engineering

Because social engineering targets people, its defenses are largely human and procedural, which makes
them the responsibility of the whole organization rather than the IT department alone. The single most
important defense is **security awareness training**: teaching employees what social engineers seek, the
psychological triggers to recognize, and the behaviors to adopt, repeated regularly rather than once at
hiring, because awareness fades. Well-run programs include simulated phishing, and many organizations
find that training delivered by an outside specialist is taken more seriously.

Training must be reinforced by **policies and procedures** that remove the burden of judgment from
individuals in the moment. *Acceptable use policies (AUPs)* define what users may and may not do.
*Help-desk verification procedures* are critical, since the help desk is a prime target: callers should
be verified through caller identification and callback, a second authentication factor, or cognitive
questions, and highly secure organizations forbid giving out or resetting passwords over the phone
altogether. *Hiring and termination policies* matter too, background and reference checks and signed
non-disclosure agreements (NDAs) at hiring, and at departure, exit interviews, immediate suspension of
access, and a checklist confirming the return of keys, badges, and devices. *Identification policies*
require visible badges, registered and escorted guests, and a culture in which employees feel empowered,
and supported by management, to challenge anyone without a badge and to report suspected attacks without
fear of blame. Practical user habits round out the defense: do not click unexpected attachments, never
share passwords, always escort guests, and do not let outsiders connect to the network without approval.

The recurring theme is that technology alone cannot stop attacks aimed at people; only a combination of
informed, empowered employees and clear procedures that make verification the default can. A reporting
culture is especially valuable, because the employee who recognizes and reports a phishing attempt turns
the human element from the weakest link into an early-warning sensor.
'''))
print("part C:", len(C))
pickle.dump(C, open(".build/_ch04.pkl","wb"))
